spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true

  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/wordNote?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username : root
    password : gimin0831
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      default_batch_fetch_size : 1000
    properties:
      hibernate:
        default_batch_fetch_size : 300
        use_sql_comments: true
        # show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace
